config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  root 'statuses#new'
  get "like/:id" => "statuses#like", :as => :like

end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :user, presence: true, uniqueness: true, allow_blank: false
  validates :status, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def index
    @statuses = Status.all.order(:id)
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      redirect_to statuses_path, notice: "Project was Created"
    else
      render :new
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])
    if @status.update(status_params)
      redirect_to statuses_path, notice: "Project was Updated"
    end
  end

  def show
    @status = Status.find(params[:id])
  end

  def destroy
    @status = Status.find(params[:id])
    if @status.destroy
      redirect_to statuses_path, notice:"Project was Deleted"
    end
  end

  def like
    @status = Status.find(params[:id])

    if @status.likes.nil?
      @status.likes = 0
    end

    @status.likes += 1

    @status.save
    redirect_to statuses_path

  end

  private

  def status_params
    params.require(:status).permit(:status, :user, :likes)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudScratchValidations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= notice %>

<%= yield %>

</body>
</html>

app/views/statuses/_form.html.erb
<% if @status.errors.any? %>

  <h2><%= pluralize(@status.errors.count, "error") %> prohibited this project from being saved:</h2>

  <ul>
    <% @status.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @status do |f| %>

<%= f.label :status %>
<%= f.text_field :status %>

<%= f.label :user %>
<%= f.text_field :user %>

<%= f.submit %>

<% end %>

app/views/statuses/index.html.erb
<% @statuses.each do |status| %>
  <p>
  <%= status.status %>
    <%= status.user %>
    <%= button_to "like", like_path(:id => status.id), method: :get %>
    <%= status.likes %>
    <%= link_to 'Edit', status_path(status) %>
    <%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

app/views/statuses/new.html.erb
<p><%= render 'form' %></p>

app/views/statuses/show.html.erb
<%= render 'form' %>